[package]
name = "drawbridge"
version = "0.1.0"
authors = ["Ben Challenor <ben@challenor.org>"]

[profile.release]
lto = true

[dependencies]
error-chain = "0.11.0"
ipnet = "1.0.0"
openssl-probe = "0.1.2"
rusoto_core = "0.30.0"
rusoto_ec2 = "0.30.0"
rusoto_route53 = "0.30.0"
